### ISSUE TITLE
does not handle oAuth flow

### ISSUE THREAD

**Issue by hansent** [johnagan/tinyspeck#1]
should the server be able to handle oAuth flow as well?  it would make it a lot easier to test a new slack app that way.

e.g. if I want to try out https://github.com/slackhq/onboarding-example, I need to create a seperate server to handle the oAuth flow just so I can add the app to my team (unless there is a way to do this in slack directly, but I haven't found one)

**Comment by johnagan** [comment]
Thanks for the comment @hansent. This is really meant to be a lightweight client that sits on top of a server, like express or even AWS lambda. I built the server function as just a helper.

I could probably add oauth flow, but I didn't build this as a production-grade web server.
