### ISSUE TITLE
http "response" isn't emitted to listeners

### ISSUE THREAD

**Issue by paulcollett** [johnagan/tinyspeck#4]
Looking to modify the response before outputting the page. From the looks of it, the response from the http library is being passed to `TinySpeck.emit` as an additional argument, though ignored when being passed along to the super. Easy fix to expose the response?

**Comment by johnagan** [comment]
>  Easy fix to expose the response?
@paulcollett not exactly. Slack requires that a 200 is returned within 3 seconds. So this code always returns a 200 and allows you to handle the event multiple times without a time limit.

>  From the looks of it, the response from the http library is being passed to TinySpeck.emit as an additional argument, though ignored when being passed along to the super

The way it's coded today is if you watch for `/path`, your callback will be `(req, res)`, but if you have a slash command named `/path` it will callback with `msg`. so you could watch for a path and handle it like an express route.
